import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next";

const roboto = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NuqsAdapter>
        <TRPCReactProvider>
          {" "}
          <html lang="en">
            <body className={`${roboto.className}  ${funnelDisplay.style}  `}>
              <Toaster />
              {children}
            </body>
          </html>
        </TRPCReactProvider>
      </NuqsAdapter>
    </>
  );
}
